fix(Package): Use prepare instead of postinstall
This avoid the following error when installing Thema in another package:

```bash
> @stencila/thema@1.6.0 postinstall /home/nokome/stencila/source/encoda/node_modules/@stencila/thema
> npm run update

> @stencila/thema@1.6.0 update /home/nokome/stencila/source/encoda/node_modules/@stencila/thema
> npm run update:selectors && npm run update:examples && npm run update:themes && npm run update:extensions

> @stencila/thema@1.6.0 update:selectors /home/nokome/stencila/source/encoda/node_modules/@stencila/thema
> ts-node --files src/scripts/selectors.ts

Error: Cannot find module '/home/nokome/stencila/source/encoda/node_modules/@stencila/thema/src/scripts/selectors.ts'
```

See https://docs.npmjs.com/misc/scripts