chore(Rust): Remove `rust-toolchain.toml`
The toolchain file seems to be only necessary if we need to pin to a particular version of Rust.
https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file.
Having a tool chain with an older version (1.58.1) was causing an issue on CI:

> error: package `async-global-executor v2.1.0` cannot be built because it requires rustc 1.5
 or newer, while the currently active rustc version is 1.58.1