chore(rust makefile): use `cargo install --locked`
Attempts to solve this:

https://github.com/stencila/stencila/actions/runs/16548046556/job/46798771759#step:14:292

```
error: failed to compile `cargo-binstall v1.14.2`, intermediate artifacts can be found at `/tmp/cargo-install064utr`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.85.1 is not supported by the following package:
    clap-cargo@0.16.0 requires rustc 1.86
  Try re-running `cargo install` with `--locked`
make[1]: *** [Makefile:20: setup] Error 101
make[1]: Leaving directory '/home/runner/work/stencila/stencila/rust'
make: *** [Makefile:5: install] Error 2
Error: Process completed with exit code 2.
```