ci(cli): remove macos-intel release build
Increasingly small numbers and no longer supported by some dependenceies e.g.

warning: ort-sys@2.0.0-rc.11: [ort-sys] [WARN] can't do xcframework linking for target 'x86_64-apple-darwin'
error: ort-sys@2.0.0-rc.11: ort does not provide prebuilt binaries for the target `x86_64-apple-darwin` with feature set (no features).
error: ort-sys@2.0.0-rc.11:  | You may have to compile ONNX Runtime from source and link `ort` to your custom build; see https://ort.pyke.io/setup/linking
error: ort-sys@2.0.0-rc.11:  | Alternatively, try a different backend like `ort-tract`; see https://ort.pyke.io/backends